# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

#source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Rodrigo Maia
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://rodrigomaia.me
baseurl: ""
# baseurl: ""

google_analytics: UA-60989222-1
repo: http://github.com/rodrigomaia17
disqus_shortname: "rodrigomaiablog"
disqus_site_shortname: "rodrigomaiablog"

# Author settings
author:
  name      : Rodrigo Maia
  job       : Full Stack Developer
  bio       : ""
  thumb     : /images/author.jpeg
  email     : rodrigo.maia.pereira@gmail.com
  url       : http://rodrigomaia.me
  github    : http://github.com/rodrigomaia17
  twitter   : http://twitter.com/rodrigomaia17
  facebook  : http://facebook.com/rodrigomaia17
  linkedin  : http://linkedin.com/in/rodrigomaia17

# navbar pages
navbar:
  #- slug: about
    #title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
